/* Folium Built-in Dictionary
   Format: word -> { ph: phonetics|null, pos: [{p: partOfSpeech, d: [definitions], e: example|null}] }
   Non-English entries: definitions are English glosses/translations. */
window.FOLIUM_DICT = (function () {
const D = {};

/* ── English ─────────────────────────────────────────────────────────────── */
D.en = {
"ability":{"ph":"/əˈbɪlɪti/","pos":[{"p":"noun","d":["The capacity or skill to do something."],"e":"She has the ability to learn quickly."}]},
"accurate":{"ph":"/ˈækjərɪt/","pos":[{"p":"adjective","d":["Free from errors; conforming exactly to truth or fact."],"e":"The report must be accurate."}]},
"achieve":{"ph":"/əˈtʃiːv/","pos":[{"p":"verb","d":["Successfully reach a goal through effort."],"e":"He achieved his dream."}]},
"adapt":{"ph":"/əˈdæpt/","pos":[{"p":"verb","d":["Adjust to new conditions.","Modify to suit a new purpose."],"e":"Animals adapt to their environment."}]},
"adequate":{"ph":"/ˈædɪkwɪt/","pos":[{"p":"adjective","d":["Satisfactory or acceptable in quality or quantity."],"e":"The resources were adequate for the task."}]},
"affect":{"ph":"/əˈfɛkt/","pos":[{"p":"verb","d":["Have an effect on; make a difference to."],"e":"The cold weather affects crop yields."}]},
"ambiguous":{"ph":"/æmˈbɪɡjuəs/","pos":[{"p":"adjective","d":["Open to more than one interpretation; unclear."],"e":"The instructions were ambiguous."}]},
"analysis":{"ph":"/əˈnæləsɪs/","pos":[{"p":"noun","d":["Detailed examination of elements or structure.","The process of separating something into its parts to understand it."],"e":"The data analysis revealed trends."}]},
"analyze":{"ph":"/ˈænəlaɪz/","pos":[{"p":"verb","d":["Examine in detail in order to understand."],"e":"Scientists analyze the samples."}]},
"appropriate":{"ph":"/əˈproʊpriɪt/","pos":[{"p":"adjective","d":["Suitable or fitting for a particular purpose."],"e":"Wear appropriate clothing for the weather."}]},
"arbitrary":{"ph":"/ˈɑːrbɪtrɛri/","pos":[{"p":"adjective","d":["Based on random choice rather than reason or system."],"e":"The decision seemed arbitrary."}]},
"aspect":{"ph":"/ˈæspɛkt/","pos":[{"p":"noun","d":["A particular part or feature of something."],"e":"Consider every aspect of the problem."}]},
"assumption":{"ph":"/əˈsʌmpʃən/","pos":[{"p":"noun","d":["Something accepted as true without proof."],"e":"The plan rests on flawed assumptions."}]},
"benefit":{"ph":"/ˈbɛnɪfɪt/","pos":[{"p":"noun","d":["An advantage or profit gained."],"e":"Exercise has many health benefits."},{"p":"verb","d":["Receive an advantage; be helped."],"e":"Everyone benefits from good communication."}]},
"catalyst":{"ph":"/ˈkætəlɪst/","pos":[{"p":"noun","d":["A substance that speeds up a reaction without being consumed.","A person or thing that precipitates an event."],"e":"The speech was a catalyst for change."}]},
"coherent":{"ph":"/koʊˈhɪərənt/","pos":[{"p":"adjective","d":["Logical and consistent; easy to understand."],"e":"She gave a coherent explanation."}]},
"complex":{"ph":"/ˈkɒmplɛks/","pos":[{"p":"adjective","d":["Consisting of many interconnected parts; not simple."],"e":"This is a complex issue."}]},
"concept":{"ph":"/ˈkɒnsɛpt/","pos":[{"p":"noun","d":["An abstract idea; a general understanding."],"e":"The concept of democracy."}]},
"conclude":{"ph":"/kənˈkluːd/","pos":[{"p":"verb","d":["Arrive at a judgment after reasoning.","Bring to an end."],"e":"We concluded that more research is needed."}]},
"consequence":{"ph":"/ˈkɒnsɪkwəns/","pos":[{"p":"noun","d":["A result or effect, typically negative."],"e":"Actions have consequences."}]},
"consistent":{"ph":"/kənˈsɪstənt/","pos":[{"p":"adjective","d":["Acting in the same way over time; not contradictory."],"e":"The results were consistent across tests."}]},
"context":{"ph":"/ˈkɒntɛkst/","pos":[{"p":"noun","d":["The circumstances surrounding an event or statement."],"e":"You must understand the historical context."}]},
"contrast":{"ph":"/ˈkɒntræst/","pos":[{"p":"noun","d":["A striking difference between two things."],"e":"The contrast between day and night."},{"p":"verb","d":["Compare to highlight differences."],"e":"Contrast these two theories."}]},
"contribute":{"ph":"/kənˈtrɪbjuːt/","pos":[{"p":"verb","d":["Help bring about a result; give something to a common purpose."],"e":"Each member must contribute."}]},
"critical":{"ph":"/ˈkrɪtɪkəl/","pos":[{"p":"adjective","d":["Expressing adverse judgment.","Of vital importance."],"e":"Critical thinking is essential."}]},
"deduce":{"ph":"/dɪˈdjuːs/","pos":[{"p":"verb","d":["Reach a conclusion by reasoning from premises."],"e":"From the clues, we deduced the answer."}]},
"define":{"ph":"/dɪˈfaɪn/","pos":[{"p":"verb","d":["State the meaning of a word or concept.","Describe exactly the nature of."],"e":"Define the term before using it."}]},
"demonstrate":{"ph":"/ˈdɛmənstreɪt/","pos":[{"p":"verb","d":["Clearly show the existence of; prove.","Show how something works."],"e":"The experiment demonstrates the principle."}]},
"describe":{"ph":"/dɪˈskraɪb/","pos":[{"p":"verb","d":["Give a detailed account of in words."],"e":"Describe what you saw."}]},
"determine":{"ph":"/dɪˈtɜːrmɪn/","pos":[{"p":"verb","d":["Cause something to occur in a particular way.","Find out conclusively."],"e":"Genetics can determine eye colour."}]},
"develop":{"ph":"/dɪˈvɛləp/","pos":[{"p":"verb","d":["Grow or cause to grow; become more advanced."],"e":"She developed a new skill."}]},
"dilemma":{"ph":"/dɪˈlɛmə/","pos":[{"p":"noun","d":["A situation requiring a choice between equally undesirable alternatives."],"e":"He faced a moral dilemma."}]},
"discuss":{"ph":"/dɪˈskʌs/","pos":[{"p":"verb","d":["Talk about a topic; examine by argument."],"e":"Let us discuss the proposal."}]},
"effect":{"ph":"/ɪˈfɛkt/","pos":[{"p":"noun","d":["A change produced by an action; a result."],"e":"The medication had a calming effect."},{"p":"verb","d":["Bring about; cause to happen."],"e":"Effect a positive change."}]},
"effective":{"ph":"/ɪˈfɛktɪv/","pos":[{"p":"adjective","d":["Producing the desired result; successful."],"e":"An effective solution."}]},
"eloquent":{"ph":"/ˈɛləkwənt/","pos":[{"p":"adjective","d":["Fluent and persuasive in speaking or writing."],"e":"She gave an eloquent speech."}]},
"empathy":{"ph":"/ˈɛmpəθi/","pos":[{"p":"noun","d":["The ability to understand and share the feelings of another."],"e":"Show empathy toward others."}]},
"empirical":{"ph":"/ɪmˈpɪrɪkəl/","pos":[{"p":"adjective","d":["Based on observation or experiment rather than theory."],"e":"Empirical evidence supports the claim."}]},
"ensure":{"ph":"/ɪnˈʃʊər/","pos":[{"p":"verb","d":["Make certain that something will occur or be the case."],"e":"Ensure all doors are locked."}]},
"ephemeral":{"ph":"/ɪˈfɛmərəl/","pos":[{"p":"adjective","d":["Lasting for a very short time."],"e":"Fame can be ephemeral."}]},
"essential":{"ph":"/ɪˈsɛnʃəl/","pos":[{"p":"adjective","d":["Absolutely necessary; extremely important."],"e":"Water is essential for life."}]},
"establish":{"ph":"/ɪˈstæblɪʃ/","pos":[{"p":"verb","d":["Set up on a firm or permanent basis.","Show something to be true."],"e":"Establish the facts first."}]},
"evaluate":{"ph":"/ɪˈvæljueɪt/","pos":[{"p":"verb","d":["Form an idea of the amount or value of; assess."],"e":"Evaluate the risks carefully."}]},
"evidence":{"ph":"/ˈɛvɪdəns/","pos":[{"p":"noun","d":["Available facts indicating whether something is true."],"e":"The evidence points to the defendant."}]},
"examine":{"ph":"/ɪɡˈzæmɪn/","pos":[{"p":"verb","d":["Inspect closely; investigate."],"e":"Examine the document carefully."}]},
"explicit":{"ph":"/ɪkˈsplɪsɪt/","pos":[{"p":"adjective","d":["Stated clearly and in detail; leaving no room for doubt."],"e":"The instructions are explicit."}]},
"factor":{"ph":"/ˈfæktər/","pos":[{"p":"noun","d":["A circumstance contributing to a result."],"e":"Cost is an important factor."}]},
"feasible":{"ph":"/ˈfiːzɪbəl/","pos":[{"p":"adjective","d":["Possible and practical to achieve easily."],"e":"Is this plan feasible?"}]},
"feature":{"ph":"/ˈfiːtʃər/","pos":[{"p":"noun","d":["A distinctive attribute or aspect."],"e":"The new feature improves performance."}]},
"framework":{"ph":"/ˈfreɪmwɜːrk/","pos":[{"p":"noun","d":["A basic structure underlying a system."],"e":"A framework for analysis."}]},
"fundamental":{"ph":"/ˌfʌndəˈmɛntəl/","pos":[{"p":"adjective","d":["Forming a necessary base; central and important."],"e":"Respect is fundamental in relationships."}]},
"global":{"ph":"/ˈɡloʊbəl/","pos":[{"p":"adjective","d":["Relating to the whole world; worldwide."],"e":"A global pandemic."}]},
"hierarchy":{"ph":"/ˈhaɪərɑːrki/","pos":[{"p":"noun","d":["A system of ranking items one above another."],"e":"A corporate hierarchy."}]},
"hypothesis":{"ph":"/haɪˈpɒθɪsɪs/","pos":[{"p":"noun","d":["A proposed explanation tested by investigation."],"e":"The hypothesis was confirmed."}]},
"identify":{"ph":"/aɪˈdɛntɪfaɪ/","pos":[{"p":"verb","d":["Establish or indicate the identity of; recognize."],"e":"Identify the problem first."}]},
"implicit":{"ph":"/ɪmˈplɪsɪt/","pos":[{"p":"adjective","d":["Suggested though not directly expressed."],"e":"There was an implicit warning in his words."}]},
"indicate":{"ph":"/ˈɪndɪkeɪt/","pos":[{"p":"verb","d":["Point out; show; be a sign of."],"e":"The data indicates an improvement."}]},
"influence":{"ph":"/ˈɪnfluəns/","pos":[{"p":"noun","d":["The capacity to have an effect on someone or something."],"e":"She had great influence over the group."},{"p":"verb","d":["Have an influence on."],"e":"Media influences public opinion."}]},
"inherent":{"ph":"/ɪnˈhɪərənt/","pos":[{"p":"adjective","d":["Existing as a permanent, essential characteristic."],"e":"There are inherent risks in the project."}]},
"innovation":{"ph":"/ˌɪnəˈveɪʃən/","pos":[{"p":"noun","d":["A new method, idea, or product."],"e":"Innovation drives progress."}]},
"insight":{"ph":"/ˈɪnsaɪt/","pos":[{"p":"noun","d":["A deep understanding of a person or thing."],"e":"The research provides key insights."}]},
"intuitive":{"ph":"/ɪnˈtjuːɪtɪv/","pos":[{"p":"adjective","d":["Based on instinct; easy to use or understand."],"e":"An intuitive user interface."}]},
"irony":{"ph":"/ˈaɪərəni/","pos":[{"p":"noun","d":["The expression of meaning using language that normally means the opposite.","A state of affairs contrary to what was expected."],"e":"The irony is that he failed the driving test."}]},
"logical":{"ph":"/ˈlɒdʒɪkəl/","pos":[{"p":"adjective","d":["Based on clear reasoning; following naturally."],"e":"A logical conclusion."}]},
"maintain":{"ph":"/meɪnˈteɪn/","pos":[{"p":"verb","d":["Keep in good condition.","Continue or preserve."],"e":"Maintain your focus."}]},
"meticulous":{"ph":"/mɪˈtɪkjʊləs/","pos":[{"p":"adjective","d":["Showing great attention to detail; very careful."],"e":"Meticulous research."}]},
"method":{"ph":"/ˈmɛθəd/","pos":[{"p":"noun","d":["A particular procedure for doing something."],"e":"A scientific method."}]},
"nuance":{"ph":"/ˈnjuːɑːns/","pos":[{"p":"noun","d":["A subtle difference in meaning or expression."],"e":"The nuances of language matter."}]},
"objective":{"ph":"/əbˈdʒɛktɪv/","pos":[{"p":"adjective","d":["Not influenced by personal feelings; impartial."],"e":"An objective assessment."},{"p":"noun","d":["A goal or aim."],"e":"Our main objective is growth."}]},
"paradigm":{"ph":"/ˈpærədaɪm/","pos":[{"p":"noun","d":["A typical pattern or model; a framework of assumptions."],"e":"A paradigm shift in thinking."}]},
"paradox":{"ph":"/ˈpærədɒks/","pos":[{"p":"noun","d":["A statement that seems contradictory but may be true."],"e":"The paradox of choice."}]},
"perspective":{"ph":"/pərˈspɛktɪv/","pos":[{"p":"noun","d":["A particular attitude or way of viewing something."],"e":"Consider the problem from a different perspective."}]},
"phenomenon":{"ph":"/fɪˈnɒmɪnən/","pos":[{"p":"noun","d":["A fact or situation that is observed to exist."],"e":"A natural phenomenon."}]},
"pragmatic":{"ph":"/præɡˈmætɪk/","pos":[{"p":"adjective","d":["Dealing with things sensibly and practically."],"e":"A pragmatic approach to the problem."}]},
"precise":{"ph":"/prɪˈsaɪs/","pos":[{"p":"adjective","d":["Marked by exactness; clearly expressed."],"e":"Precise measurements are needed."}]},
"prerequisite":{"ph":"/priːˈrɛkwɪzɪt/","pos":[{"p":"noun","d":["Something required as a prior condition."],"e":"Statistics is a prerequisite for this course."}]},
"principle":{"ph":"/ˈprɪnsɪpəl/","pos":[{"p":"noun","d":["A fundamental truth or proposition.","A rule of conduct."],"e":"The principle of equality."}]},
"profound":{"ph":"/prəˈfaʊnd/","pos":[{"p":"adjective","d":["Having or showing great knowledge; very intense."],"e":"A profound impact."}]},
"relevant":{"ph":"/ˈrɛlɪvənt/","pos":[{"p":"adjective","d":["Closely connected to the matter at hand."],"e":"Choose relevant examples."}]},
"resilient":{"ph":"/rɪˈzɪliənt/","pos":[{"p":"adjective","d":["Able to recover quickly from difficulties."],"e":"A resilient community."}]},
"serendipity":{"ph":"/ˌsɛrənˈdɪpɪti/","pos":[{"p":"noun","d":["The occurrence of happy events by chance."],"e":"They met by serendipity."}]},
"significant":{"ph":"/sɪɡˈnɪfɪkənt/","pos":[{"p":"adjective","d":["Sufficiently great to be noteworthy."],"e":"A significant increase."}]},
"subjective":{"ph":"/səbˈdʒɛktɪv/","pos":[{"p":"adjective","d":["Based on personal feelings rather than facts."],"e":"Taste is subjective."}]},
"substantial":{"ph":"/səbˈstænʃəl/","pos":[{"p":"adjective","d":["Of considerable importance or size."],"e":"A substantial amount of work."}]},
"systematic":{"ph":"/ˌsɪstəˈmætɪk/","pos":[{"p":"adjective","d":["Done or acting according to a fixed plan; methodical."],"e":"A systematic approach."}]},
"tangible":{"ph":"/ˈtændʒɪbəl/","pos":[{"p":"adjective","d":["Perceptible by touch; clear and definite."],"e":"Tangible results."}]},
"thorough":{"ph":"/ˈθʌrə/","pos":[{"p":"adjective","d":["Complete with attention to every detail."],"e":"A thorough investigation."}]},
"transparent":{"ph":"/trænsˈpærənt/","pos":[{"p":"adjective","d":["Easy to see through; open and honest."],"e":"A transparent process."}]},
"ubiquitous":{"ph":"/juːˈbɪkwɪtəs/","pos":[{"p":"adjective","d":["Present everywhere at the same time."],"e":"Smartphones are ubiquitous."}]},
"unique":{"ph":"/juːˈniːk/","pos":[{"p":"adjective","d":["Being the only one of its kind."],"e":"Each person is unique."}]},
"valid":{"ph":"/ˈvælɪd/","pos":[{"p":"adjective","d":["Logically sound; legally acceptable."],"e":"A valid argument."}]},
"versatile":{"ph":"/ˈvɜːrsətaɪl/","pos":[{"p":"adjective","d":["Able to adapt to many uses or functions."],"e":"A versatile tool."}]},
"virtual":{"ph":"/ˈvɜːrtʃuəl/","pos":[{"p":"adjective","d":["Almost or nearly as described; simulated by computer."],"e":"A virtual meeting."}]},
"nostalgia":{"ph":"/nɒˈstældʒə/","pos":[{"p":"noun","d":["Sentimental longing for the past."],"e":"A wave of nostalgia for childhood."}]},
"melancholy":{"ph":"/ˈmɛlənkɒli/","pos":[{"p":"noun","d":["A feeling of pensive sadness."],"e":"A mood of quiet melancholy."},{"p":"adjective","d":["Sad and thoughtful."],"e":"A melancholy expression."}]},
"peculiar":{"ph":"/pɪˈkjuːliər/","pos":[{"p":"adjective","d":["Strange or unusual; distinctive to a place or person."],"e":"A peculiar smell."}]},
"absurd":{"ph":"/əbˈsɜːrd/","pos":[{"p":"adjective","d":["Wildly unreasonable or inappropriate."],"e":"An absurd proposal."}]},
"ethical":{"ph":"/ˈɛθɪkəl/","pos":[{"p":"adjective","d":["Relating to moral principles; morally correct."],"e":"An ethical decision."}]},
"colleague":{"ph":"/ˈkɒliːɡ/","pos":[{"p":"noun","d":["A fellow worker in a profession or organization."],"e":"I consulted my colleague."}]},
"collaborate":{"ph":"/kəˈlæbəreɪt/","pos":[{"p":"verb","d":["Work jointly on an activity or project."],"e":"Teams must collaborate."}]},
"implement":{"ph":"/ˈɪmplɪmɛnt/","pos":[{"p":"verb","d":["Put a decision or plan into effect."],"e":"Implement the strategy."},{"p":"noun","d":["A tool or instrument."],"e":"A farming implement."}]},
"initiative":{"ph":"/ɪˈnɪʃətɪv/","pos":[{"p":"noun","d":["The ability to act independently; a new plan."],"e":"Take the initiative."}]},
"priority":{"ph":"/praɪˈɒrɪti/","pos":[{"p":"noun","d":["A thing given greater importance over others."],"e":"Safety is the top priority."}]},
"strategy":{"ph":"/ˈstrætɪdʒi/","pos":[{"p":"noun","d":["A plan designed to achieve a goal."],"e":"A marketing strategy."}]},
"challenge":{"ph":"/ˈtʃælɪndʒ/","pos":[{"p":"noun","d":["A difficult task or situation."],"e":"Face every challenge."},{"p":"verb","d":["Dispute or question."],"e":"Challenge the assumption."}]},
"communicate":{"ph":"/kəˈmjuːnɪkeɪt/","pos":[{"p":"verb","d":["Share or exchange information."],"e":"Communicate clearly."}]},
"potential":{"ph":"/pəˈtɛnʃəl/","pos":[{"p":"adjective","d":["Having the capacity to develop into something."],"e":"A potential problem."},{"p":"noun","d":["Latent qualities or abilities."],"e":"Fulfill your potential."}]},
"process":{"ph":"/ˈprɒsɛs/","pos":[{"p":"noun","d":["A series of actions producing a result."],"e":"A manufacturing process."},{"p":"verb","d":["Perform a series of operations on."],"e":"Process the data."}]},
"resource":{"ph":"/ˈriːsɔːrs/","pos":[{"p":"noun","d":["A stock of assets available when needed."],"e":"Natural resources."}]},
"structure":{"ph":"/ˈstrʌktʃər/","pos":[{"p":"noun","d":["The arrangement of parts in a whole."],"e":"The structure of the sentence."}]},
"support":{"ph":"/səˈpɔːrt/","pos":[{"p":"verb","d":["Bear the weight of; help or encourage."],"e":"Support your team."},{"p":"noun","d":["Assistance."],"e":"Emotional support."}]},
"interpret":{"ph":"/ɪnˈtɜːrprɪt/","pos":[{"p":"verb","d":["Explain the meaning of; translate orally."],"e":"Interpret the data."}]},
"justify":{"ph":"/ˈdʒʌstɪfaɪ/","pos":[{"p":"verb","d":["Show or prove to be right or reasonable."],"e":"Justify your decision."}]},
"perceive":{"ph":"/pərˈsiːv/","pos":[{"p":"verb","d":["Become aware of through the senses; interpret."],"e":"How do you perceive this problem?"}]}
};

/* ── Spanish ─────────────────────────────────────────────────────────────── */
D.es = {
"hola":{"pos":[{"p":"interjection","d":["Hello; a common Spanish greeting."]}]},
"adiós":{"pos":[{"p":"interjection","d":["Goodbye; farewell in Spanish."]}]},
"gracias":{"pos":[{"p":"interjection","d":["Thank you."]}]},
"por favor":{"pos":[{"p":"phrase","d":["Please; used when making a polite request."]}]},
"perdón":{"pos":[{"p":"interjection","d":["Excuse me; sorry; pardon."]}]},
"sí":{"pos":[{"p":"adverb","d":["Yes."]}]},
"no":{"pos":[{"p":"adverb","d":["No; negation."]}]},
"agua":{"pos":[{"p":"noun","d":["Water."]}]},
"casa":{"pos":[{"p":"noun","d":["House; home; building where people live."]}]},
"persona":{"pos":[{"p":"noun","d":["Person; human being."]}]},
"tiempo":{"pos":[{"p":"noun","d":["Time; also weather."]}]},
"trabajo":{"pos":[{"p":"noun","d":["Work; job; employment."]}]},
"dinero":{"pos":[{"p":"noun","d":["Money."]}]},
"día":{"pos":[{"p":"noun","d":["Day."]}]},
"año":{"pos":[{"p":"noun","d":["Year."]}]},
"libro":{"pos":[{"p":"noun","d":["Book."]}]},
"ciudad":{"pos":[{"p":"noun","d":["City; town."]}]},
"país":{"pos":[{"p":"noun","d":["Country; nation."]}]},
"vida":{"pos":[{"p":"noun","d":["Life."]}]},
"amor":{"pos":[{"p":"noun","d":["Love."]}]},
"familia":{"pos":[{"p":"noun","d":["Family."]}]},
"amigo":{"pos":[{"p":"noun","d":["Friend (masculine)."]}]},
"amiga":{"pos":[{"p":"noun","d":["Friend (feminine)."]}]},
"comida":{"pos":[{"p":"noun","d":["Food; meal."]}]},
"nombre":{"pos":[{"p":"noun","d":["Name."]}]},
"bueno":{"pos":[{"p":"adjective","d":["Good."]}]},
"malo":{"pos":[{"p":"adjective","d":["Bad; evil."]}]},
"grande":{"pos":[{"p":"adjective","d":["Big; large; great."]}]},
"pequeño":{"pos":[{"p":"adjective","d":["Small; little."]}]},
"bonito":{"pos":[{"p":"adjective","d":["Beautiful; pretty; nice."]}]},
"nuevo":{"pos":[{"p":"adjective","d":["New."]}]},
"viejo":{"pos":[{"p":"adjective","d":["Old."]}]},
"importante":{"pos":[{"p":"adjective","d":["Important."]}]},
"ser":{"pos":[{"p":"verb","d":["To be (permanent qualities, identity, origin)."]}]},
"estar":{"pos":[{"p":"verb","d":["To be (state, condition, location)."]}]},
"tener":{"pos":[{"p":"verb","d":["To have; to possess."]}]},
"hacer":{"pos":[{"p":"verb","d":["To do; to make."]}]},
"ir":{"pos":[{"p":"verb","d":["To go."]}]},
"venir":{"pos":[{"p":"verb","d":["To come."]}]},
"poder":{"pos":[{"p":"verb","d":["To be able to; can."]}]},
"querer":{"pos":[{"p":"verb","d":["To want; to love (a person)."]}]},
"saber":{"pos":[{"p":"verb","d":["To know (a fact, skill)."]}]},
"hablar":{"pos":[{"p":"verb","d":["To speak; to talk."]}]},
"comer":{"pos":[{"p":"verb","d":["To eat."]}]},
"beber":{"pos":[{"p":"verb","d":["To drink."]}]},
"dormir":{"pos":[{"p":"verb","d":["To sleep."]}]},
"uno":{"pos":[{"p":"numeral","d":["One (1)."]}]},
"dos":{"pos":[{"p":"numeral","d":["Two (2)."]}]},
"tres":{"pos":[{"p":"numeral","d":["Three (3)."]}]},
"cuatro":{"pos":[{"p":"numeral","d":["Four (4)."]}]},
"cinco":{"pos":[{"p":"numeral","d":["Five (5)."]}]},
"diez":{"pos":[{"p":"numeral","d":["Ten (10)."]}]},
"rojo":{"pos":[{"p":"adjective","d":["Red."]}]},
"azul":{"pos":[{"p":"adjective","d":["Blue."]}]},
"verde":{"pos":[{"p":"adjective","d":["Green."]}]},
"blanco":{"pos":[{"p":"adjective","d":["White."]}]},
"negro":{"pos":[{"p":"adjective","d":["Black."]}]},
"hoy":{"pos":[{"p":"adverb","d":["Today."]}]},
"mañana":{"pos":[{"p":"noun","d":["Tomorrow; also morning."]}]},
"ayer":{"pos":[{"p":"adverb","d":["Yesterday."]}]},
"ahora":{"pos":[{"p":"adverb","d":["Now."]}]},
"siempre":{"pos":[{"p":"adverb","d":["Always."]}]},
"nunca":{"pos":[{"p":"adverb","d":["Never."]}]},
"aquí":{"pos":[{"p":"adverb","d":["Here."]}]},
"allí":{"pos":[{"p":"adverb","d":["There."]}]},
"muy":{"pos":[{"p":"adverb","d":["Very."]}]},
"mucho":{"pos":[{"p":"adverb","d":["A lot; much; many."]}]},
"poco":{"pos":[{"p":"adverb","d":["A little; few."]}]},
"bien":{"pos":[{"p":"adverb","d":["Well; fine; good."]}]},
"mal":{"pos":[{"p":"adverb","d":["Badly; poorly."]}]},
"porque":{"pos":[{"p":"conjunction","d":["Because."]}]},
"pero":{"pos":[{"p":"conjunction","d":["But; however."]}]},
"cuando":{"pos":[{"p":"conjunction","d":["When."]}]},
"mundo":{"pos":[{"p":"noun","d":["World."]}]},
"escuela":{"pos":[{"p":"noun","d":["School."]}]},
"calle":{"pos":[{"p":"noun","d":["Street; road."]}]},
"madre":{"pos":[{"p":"noun","d":["Mother."]}]},
"padre":{"pos":[{"p":"noun","d":["Father."]}]},
"hijo":{"pos":[{"p":"noun","d":["Son; child (masculine)."]}]},
"hija":{"pos":[{"p":"noun","d":["Daughter; child (feminine)."]}]},
"empresa":{"pos":[{"p":"noun","d":["Company; business; firm."]}]},
"proyecto":{"pos":[{"p":"noun","d":["Project; plan."]}]},
"resultado":{"pos":[{"p":"noun","d":["Result; outcome."]}]},
"problema":{"pos":[{"p":"noun","d":["Problem; issue."]}]},
"solución":{"pos":[{"p":"noun","d":["Solution; answer."]}]}
};

/* ── French ──────────────────────────────────────────────────────────────── */
D.fr = {
"bonjour":{"pos":[{"p":"interjection","d":["Hello; good morning/afternoon; a standard French greeting."]}]},
"bonsoir":{"pos":[{"p":"interjection","d":["Good evening."]}]},
"au revoir":{"pos":[{"p":"phrase","d":["Goodbye; farewell."]}]},
"merci":{"pos":[{"p":"interjection","d":["Thank you."]}]},
"s'il vous plaît":{"pos":[{"p":"phrase","d":["Please (formal/plural)."]}]},
"excusez-moi":{"pos":[{"p":"phrase","d":["Excuse me; I'm sorry (formal)."]}]},
"oui":{"pos":[{"p":"adverb","d":["Yes."]}]},
"non":{"pos":[{"p":"adverb","d":["No."]}]},
"eau":{"pos":[{"p":"noun","d":["Water."]}]},
"maison":{"pos":[{"p":"noun","d":["House; home."]}]},
"personne":{"pos":[{"p":"noun","d":["Person; also nobody (with negation)."]}]},
"temps":{"pos":[{"p":"noun","d":["Time; also weather."]}]},
"travail":{"pos":[{"p":"noun","d":["Work; job."]}]},
"argent":{"pos":[{"p":"noun","d":["Money; also silver."]}]},
"jour":{"pos":[{"p":"noun","d":["Day."]}]},
"année":{"pos":[{"p":"noun","d":["Year."]}]},
"vie":{"pos":[{"p":"noun","d":["Life."]}]},
"amour":{"pos":[{"p":"noun","d":["Love."]}]},
"ami":{"pos":[{"p":"noun","d":["Friend (masculine)."]}]},
"amie":{"pos":[{"p":"noun","d":["Friend (feminine)."]}]},
"nourriture":{"pos":[{"p":"noun","d":["Food."]}]},
"nom":{"pos":[{"p":"noun","d":["Name; surname."]}]},
"bon":{"pos":[{"p":"adjective","d":["Good; kind."]}]},
"mauvais":{"pos":[{"p":"adjective","d":["Bad; poor."]}]},
"grand":{"pos":[{"p":"adjective","d":["Big; tall; great."]}]},
"petit":{"pos":[{"p":"adjective","d":["Small; little; short."]}]},
"beau":{"pos":[{"p":"adjective","d":["Beautiful; handsome."]}]},
"nouveau":{"pos":[{"p":"adjective","d":["New."]}]},
"important":{"pos":[{"p":"adjective","d":["Important."]}]},
"être":{"pos":[{"p":"verb","d":["To be."]}]},
"avoir":{"pos":[{"p":"verb","d":["To have."]}]},
"faire":{"pos":[{"p":"verb","d":["To do; to make."]}]},
"aller":{"pos":[{"p":"verb","d":["To go."]}]},
"venir":{"pos":[{"p":"verb","d":["To come."]}]},
"pouvoir":{"pos":[{"p":"verb","d":["To be able to; can."]}]},
"vouloir":{"pos":[{"p":"verb","d":["To want; to wish."]}]},
"savoir":{"pos":[{"p":"verb","d":["To know (a fact or skill)."]}]},
"parler":{"pos":[{"p":"verb","d":["To speak; to talk."]}]},
"manger":{"pos":[{"p":"verb","d":["To eat."]}]},
"boire":{"pos":[{"p":"verb","d":["To drink."]}]},
"voir":{"pos":[{"p":"verb","d":["To see."]}]},
"aujourd'hui":{"pos":[{"p":"adverb","d":["Today."]}]},
"demain":{"pos":[{"p":"adverb","d":["Tomorrow."]}]},
"hier":{"pos":[{"p":"adverb","d":["Yesterday."]}]},
"maintenant":{"pos":[{"p":"adverb","d":["Now."]}]},
"toujours":{"pos":[{"p":"adverb","d":["Always; still."]}]},
"jamais":{"pos":[{"p":"adverb","d":["Never; ever (in negative sentences)."]}]},
"beaucoup":{"pos":[{"p":"adverb","d":["A lot; much; many."]}]},
"très":{"pos":[{"p":"adverb","d":["Very."]}]},
"bien":{"pos":[{"p":"adverb","d":["Well; fine."]}]},
"parce que":{"pos":[{"p":"conjunction","d":["Because."]}]},
"mais":{"pos":[{"p":"conjunction","d":["But; however."]}]},
"monde":{"pos":[{"p":"noun","d":["World; people."]}]},
"école":{"pos":[{"p":"noun","d":["School."]}]},
"rue":{"pos":[{"p":"noun","d":["Street."]}]},
"mère":{"pos":[{"p":"noun","d":["Mother."]}]},
"père":{"pos":[{"p":"noun","d":["Father."]}]},
"enfant":{"pos":[{"p":"noun","d":["Child."]}]},
"entreprise":{"pos":[{"p":"noun","d":["Company; business; enterprise."]}]},
"résultat":{"pos":[{"p":"noun","d":["Result; outcome."]}]},
"problème":{"pos":[{"p":"noun","d":["Problem; issue."]}]},
"solution":{"pos":[{"p":"noun","d":["Solution."]}]},
"rouge":{"pos":[{"p":"adjective","d":["Red."]}]},
"bleu":{"pos":[{"p":"adjective","d":["Blue."]}]},
"vert":{"pos":[{"p":"adjective","d":["Green."]}]},
"blanc":{"pos":[{"p":"adjective","d":["White."]}]},
"noir":{"pos":[{"p":"adjective","d":["Black."]}]}
};

/* ── German ──────────────────────────────────────────────────────────────── */
D.de = {
"hallo":{"pos":[{"p":"interjection","d":["Hello; a common German greeting."]}]},
"guten morgen":{"pos":[{"p":"phrase","d":["Good morning."]}]},
"guten tag":{"pos":[{"p":"phrase","d":["Good day; hello (formal daytime greeting)."]}]},
"auf wiedersehen":{"pos":[{"p":"phrase","d":["Goodbye; until we meet again (formal)."]}]},
"tschüss":{"pos":[{"p":"interjection","d":["Bye; goodbye (informal)."]}]},
"danke":{"pos":[{"p":"interjection","d":["Thank you."]}]},
"bitte":{"pos":[{"p":"interjection","d":["Please; you're welcome."]}]},
"entschuldigung":{"pos":[{"p":"interjection","d":["Excuse me; sorry."]}]},
"ja":{"pos":[{"p":"adverb","d":["Yes."]}]},
"nein":{"pos":[{"p":"adverb","d":["No."]}]},
"wasser":{"pos":[{"p":"noun","d":["Water."]}]},
"haus":{"pos":[{"p":"noun","d":["House; home."]}]},
"person":{"pos":[{"p":"noun","d":["Person."]}]},
"zeit":{"pos":[{"p":"noun","d":["Time."]}]},
"arbeit":{"pos":[{"p":"noun","d":["Work; job; labour."]}]},
"geld":{"pos":[{"p":"noun","d":["Money."]}]},
"tag":{"pos":[{"p":"noun","d":["Day."]}]},
"jahr":{"pos":[{"p":"noun","d":["Year."]}]},
"leben":{"pos":[{"p":"noun","d":["Life."]},{"p":"verb","d":["To live."]}]},
"liebe":{"pos":[{"p":"noun","d":["Love."]}]},
"freund":{"pos":[{"p":"noun","d":["Friend; boyfriend (masculine)."]}]},
"freundin":{"pos":[{"p":"noun","d":["Friend; girlfriend (feminine)."]}]},
"essen":{"pos":[{"p":"noun","d":["Food; meal."]},{"p":"verb","d":["To eat."]}]},
"name":{"pos":[{"p":"noun","d":["Name."]}]},
"gut":{"pos":[{"p":"adjective","d":["Good; fine; well."]}]},
"schlecht":{"pos":[{"p":"adjective","d":["Bad; poor."]}]},
"groß":{"pos":[{"p":"adjective","d":["Big; tall; large."]}]},
"klein":{"pos":[{"p":"adjective","d":["Small; little."]}]},
"schön":{"pos":[{"p":"adjective","d":["Beautiful; lovely; nice."]}]},
"neu":{"pos":[{"p":"adjective","d":["New."]}]},
"alt":{"pos":[{"p":"adjective","d":["Old."]}]},
"wichtig":{"pos":[{"p":"adjective","d":["Important."]}]},
"sein":{"pos":[{"p":"verb","d":["To be."]}]},
"haben":{"pos":[{"p":"verb","d":["To have."]}]},
"machen":{"pos":[{"p":"verb","d":["To make; to do."]}]},
"gehen":{"pos":[{"p":"verb","d":["To go; to walk."]}]},
"kommen":{"pos":[{"p":"verb","d":["To come."]}]},
"können":{"pos":[{"p":"verb","d":["To be able to; can."]}]},
"wollen":{"pos":[{"p":"verb","d":["To want."]}]},
"wissen":{"pos":[{"p":"verb","d":["To know (a fact)."]}]},
"sprechen":{"pos":[{"p":"verb","d":["To speak; to talk."]}]},
"trinken":{"pos":[{"p":"verb","d":["To drink."]}]},
"sehen":{"pos":[{"p":"verb","d":["To see."]}]},
"heute":{"pos":[{"p":"adverb","d":["Today."]}]},
"morgen":{"pos":[{"p":"adverb","d":["Tomorrow; also morning (noun)."]}]},
"gestern":{"pos":[{"p":"adverb","d":["Yesterday."]}]},
"jetzt":{"pos":[{"p":"adverb","d":["Now."]}]},
"immer":{"pos":[{"p":"adverb","d":["Always."]}]},
"nie":{"pos":[{"p":"adverb","d":["Never."]}]},
"sehr":{"pos":[{"p":"adverb","d":["Very."]}]},
"viel":{"pos":[{"p":"adverb","d":["Much; a lot; many."]}]},
"weil":{"pos":[{"p":"conjunction","d":["Because."]}]},
"aber":{"pos":[{"p":"conjunction","d":["But; however."]}]},
"welt":{"pos":[{"p":"noun","d":["World."]}]},
"schule":{"pos":[{"p":"noun","d":["School."]}]},
"straße":{"pos":[{"p":"noun","d":["Street; road."]}]},
"mutter":{"pos":[{"p":"noun","d":["Mother."]}]},
"vater":{"pos":[{"p":"noun","d":["Father."]}]},
"kind":{"pos":[{"p":"noun","d":["Child."]}]},
"unternehmen":{"pos":[{"p":"noun","d":["Company; enterprise; business."]}]},
"ergebnis":{"pos":[{"p":"noun","d":["Result; outcome."]}]},
"problem":{"pos":[{"p":"noun","d":["Problem; issue."]}]},
"lösung":{"pos":[{"p":"noun","d":["Solution; answer."]}]},
"rot":{"pos":[{"p":"adjective","d":["Red."]}]},
"blau":{"pos":[{"p":"adjective","d":["Blue."]}]},
"grün":{"pos":[{"p":"adjective","d":["Green."]}]},
"weiß":{"pos":[{"p":"adjective","d":["White."]}]},
"schwarz":{"pos":[{"p":"adjective","d":["Black."]}]}
};

/* ── Italian ─────────────────────────────────────────────────────────────── */
D.it = {
"ciao":{"pos":[{"p":"interjection","d":["Hello; hi; also goodbye (informal)."]}]},
"buongiorno":{"pos":[{"p":"interjection","d":["Good morning; good day."]}]},
"arrivederci":{"pos":[{"p":"interjection","d":["Goodbye (formal)."]}]},
"grazie":{"pos":[{"p":"interjection","d":["Thank you."]}]},
"prego":{"pos":[{"p":"interjection","d":["You're welcome; please."]}]},
"scusi":{"pos":[{"p":"interjection","d":["Excuse me; sorry (formal)."]}]},
"sì":{"pos":[{"p":"adverb","d":["Yes."]}]},
"no":{"pos":[{"p":"adverb","d":["No."]}]},
"acqua":{"pos":[{"p":"noun","d":["Water."]}]},
"casa":{"pos":[{"p":"noun","d":["House; home."]}]},
"tempo":{"pos":[{"p":"noun","d":["Time; weather."]}]},
"lavoro":{"pos":[{"p":"noun","d":["Work; job."]}]},
"soldi":{"pos":[{"p":"noun","d":["Money."]}]},
"giorno":{"pos":[{"p":"noun","d":["Day."]}]},
"anno":{"pos":[{"p":"noun","d":["Year."]}]},
"vita":{"pos":[{"p":"noun","d":["Life."]}]},
"amore":{"pos":[{"p":"noun","d":["Love."]}]},
"amico":{"pos":[{"p":"noun","d":["Friend (masculine)."]}]},
"amica":{"pos":[{"p":"noun","d":["Friend (feminine)."]}]},
"cibo":{"pos":[{"p":"noun","d":["Food."]}]},
"nome":{"pos":[{"p":"noun","d":["Name."]}]},
"buono":{"pos":[{"p":"adjective","d":["Good; kind."]}]},
"cattivo":{"pos":[{"p":"adjective","d":["Bad; wicked."]}]},
"grande":{"pos":[{"p":"adjective","d":["Big; large; great."]}]},
"piccolo":{"pos":[{"p":"adjective","d":["Small; little."]}]},
"bello":{"pos":[{"p":"adjective","d":["Beautiful; nice; good-looking."]}]},
"nuovo":{"pos":[{"p":"adjective","d":["New."]}]},
"importante":{"pos":[{"p":"adjective","d":["Important."]}]},
"essere":{"pos":[{"p":"verb","d":["To be."]}]},
"avere":{"pos":[{"p":"verb","d":["To have."]}]},
"fare":{"pos":[{"p":"verb","d":["To do; to make."]}]},
"andare":{"pos":[{"p":"verb","d":["To go."]}]},
"venire":{"pos":[{"p":"verb","d":["To come."]}]},
"potere":{"pos":[{"p":"verb","d":["To be able to; can."]}]},
"volere":{"pos":[{"p":"verb","d":["To want."]}]},
"sapere":{"pos":[{"p":"verb","d":["To know (a fact)."]}]},
"parlare":{"pos":[{"p":"verb","d":["To speak; to talk."]}]},
"mangiare":{"pos":[{"p":"verb","d":["To eat."]}]},
"vedere":{"pos":[{"p":"verb","d":["To see."]}]},
"oggi":{"pos":[{"p":"adverb","d":["Today."]}]},
"domani":{"pos":[{"p":"adverb","d":["Tomorrow."]}]},
"ieri":{"pos":[{"p":"adverb","d":["Yesterday."]}]},
"adesso":{"pos":[{"p":"adverb","d":["Now."]}]},
"sempre":{"pos":[{"p":"adverb","d":["Always."]}]},
"mai":{"pos":[{"p":"adverb","d":["Never; ever."]}]},
"molto":{"pos":[{"p":"adverb","d":["Very; much; a lot."]}]},
"perché":{"pos":[{"p":"conjunction","d":["Because; why."]}]},
"ma":{"pos":[{"p":"conjunction","d":["But."]}]},
"mondo":{"pos":[{"p":"noun","d":["World."]}]},
"scuola":{"pos":[{"p":"noun","d":["School."]}]},
"madre":{"pos":[{"p":"noun","d":["Mother."]}]},
"padre":{"pos":[{"p":"noun","d":["Father."]}]},
"figlio":{"pos":[{"p":"noun","d":["Son; child (masculine)."]}]},
"rosso":{"pos":[{"p":"adjective","d":["Red."]}]},
"blu":{"pos":[{"p":"adjective","d":["Blue."]}]},
"verde":{"pos":[{"p":"adjective","d":["Green."]}]},
"bianco":{"pos":[{"p":"adjective","d":["White."]}]},
"nero":{"pos":[{"p":"adjective","d":["Black."]}]}
};

/* ── Portuguese ──────────────────────────────────────────────────────────── */
D.pt = {
"olá":{"pos":[{"p":"interjection","d":["Hello."]}]},
"oi":{"pos":[{"p":"interjection","d":["Hi (informal Brazilian greeting)."]}]},
"tchau":{"pos":[{"p":"interjection","d":["Bye; goodbye (informal, Brazilian)."]}]},
"adeus":{"pos":[{"p":"interjection","d":["Goodbye; farewell."]}]},
"obrigado":{"pos":[{"p":"interjection","d":["Thank you (masculine speaker)."]}]},
"obrigada":{"pos":[{"p":"interjection","d":["Thank you (feminine speaker)."]}]},
"por favor":{"pos":[{"p":"phrase","d":["Please."]}]},
"desculpe":{"pos":[{"p":"interjection","d":["Sorry; excuse me."]}]},
"sim":{"pos":[{"p":"adverb","d":["Yes."]}]},
"não":{"pos":[{"p":"adverb","d":["No."]}]},
"água":{"pos":[{"p":"noun","d":["Water."]}]},
"casa":{"pos":[{"p":"noun","d":["House; home."]}]},
"pessoa":{"pos":[{"p":"noun","d":["Person."]}]},
"tempo":{"pos":[{"p":"noun","d":["Time; weather."]}]},
"trabalho":{"pos":[{"p":"noun","d":["Work; job."]}]},
"dinheiro":{"pos":[{"p":"noun","d":["Money."]}]},
"dia":{"pos":[{"p":"noun","d":["Day."]}]},
"ano":{"pos":[{"p":"noun","d":["Year."]}]},
"vida":{"pos":[{"p":"noun","d":["Life."]}]},
"amor":{"pos":[{"p":"noun","d":["Love."]}]},
"amigo":{"pos":[{"p":"noun","d":["Friend (masculine)."]}]},
"comida":{"pos":[{"p":"noun","d":["Food."]}]},
"nome":{"pos":[{"p":"noun","d":["Name."]}]},
"bom":{"pos":[{"p":"adjective","d":["Good (masculine)."]}]},
"boa":{"pos":[{"p":"adjective","d":["Good (feminine)."]}]},
"ruim":{"pos":[{"p":"adjective","d":["Bad."]}]},
"grande":{"pos":[{"p":"adjective","d":["Big; large; great."]}]},
"pequeno":{"pos":[{"p":"adjective","d":["Small; little."]}]},
"bonito":{"pos":[{"p":"adjective","d":["Beautiful; pretty."]}]},
"novo":{"pos":[{"p":"adjective","d":["New; young."]}]},
"importante":{"pos":[{"p":"adjective","d":["Important."]}]},
"ser":{"pos":[{"p":"verb","d":["To be (permanent state)."]}]},
"estar":{"pos":[{"p":"verb","d":["To be (temporary state, location)."]}]},
"ter":{"pos":[{"p":"verb","d":["To have."]}]},
"fazer":{"pos":[{"p":"verb","d":["To do; to make."]}]},
"ir":{"pos":[{"p":"verb","d":["To go."]}]},
"vir":{"pos":[{"p":"verb","d":["To come."]}]},
"poder":{"pos":[{"p":"verb","d":["To be able to; can."]}]},
"querer":{"pos":[{"p":"verb","d":["To want."]}]},
"falar":{"pos":[{"p":"verb","d":["To speak; to talk."]}]},
"comer":{"pos":[{"p":"verb","d":["To eat."]}]},
"hoje":{"pos":[{"p":"adverb","d":["Today."]}]},
"amanhã":{"pos":[{"p":"adverb","d":["Tomorrow."]}]},
"ontem":{"pos":[{"p":"adverb","d":["Yesterday."]}]},
"agora":{"pos":[{"p":"adverb","d":["Now."]}]},
"sempre":{"pos":[{"p":"adverb","d":["Always."]}]},
"nunca":{"pos":[{"p":"adverb","d":["Never."]}]},
"muito":{"pos":[{"p":"adverb","d":["Very; much; a lot."]}]},
"porque":{"pos":[{"p":"conjunction","d":["Because."]}]},
"mas":{"pos":[{"p":"conjunction","d":["But."]}]},
"mundo":{"pos":[{"p":"noun","d":["World."]}]},
"escola":{"pos":[{"p":"noun","d":["School."]}]},
"mãe":{"pos":[{"p":"noun","d":["Mother."]}]},
"pai":{"pos":[{"p":"noun","d":["Father."]}]},
"filho":{"pos":[{"p":"noun","d":["Son."]}]},
"vermelho":{"pos":[{"p":"adjective","d":["Red."]}]},
"azul":{"pos":[{"p":"adjective","d":["Blue."]}]},
"verde":{"pos":[{"p":"adjective","d":["Green."]}]},
"branco":{"pos":[{"p":"adjective","d":["White."]}]},
"preto":{"pos":[{"p":"adjective","d":["Black."]}]}
};

/* ── Russian ─────────────────────────────────────────────────────────────── */
D.ru = {
"привет":{"pos":[{"p":"interjection","d":["Hi; hello (informal)."]}]},
"здравствуйте":{"pos":[{"p":"interjection","d":["Hello (formal greeting)."]}]},
"до свидания":{"pos":[{"p":"phrase","d":["Goodbye (formal)."]}]},
"пока":{"pos":[{"p":"interjection","d":["Bye (informal)."]}]},
"спасибо":{"pos":[{"p":"interjection","d":["Thank you."]}]},
"пожалуйста":{"pos":[{"p":"interjection","d":["Please; you're welcome."]}]},
"извините":{"pos":[{"p":"interjection","d":["Excuse me; sorry (formal)."]}]},
"да":{"pos":[{"p":"adverb","d":["Yes."]}]},
"нет":{"pos":[{"p":"adverb","d":["No."]}]},
"вода":{"pos":[{"p":"noun","d":["Water."]}]},
"дом":{"pos":[{"p":"noun","d":["House; home; building."]}]},
"человек":{"pos":[{"p":"noun","d":["Person; human being."]}]},
"время":{"pos":[{"p":"noun","d":["Time."]}]},
"работа":{"pos":[{"p":"noun","d":["Work; job."]}]},
"деньги":{"pos":[{"p":"noun","d":["Money."]}]},
"день":{"pos":[{"p":"noun","d":["Day."]}]},
"год":{"pos":[{"p":"noun","d":["Year."]}]},
"жизнь":{"pos":[{"p":"noun","d":["Life."]}]},
"любовь":{"pos":[{"p":"noun","d":["Love."]}]},
"друг":{"pos":[{"p":"noun","d":["Friend (masculine)."]}]},
"подруга":{"pos":[{"p":"noun","d":["Friend (feminine)."]}]},
"еда":{"pos":[{"p":"noun","d":["Food."]}]},
"имя":{"pos":[{"p":"noun","d":["First name."]}]},
"хороший":{"pos":[{"p":"adjective","d":["Good."]}]},
"плохой":{"pos":[{"p":"adjective","d":["Bad."]}]},
"большой":{"pos":[{"p":"adjective","d":["Big; large."]}]},
"маленький":{"pos":[{"p":"adjective","d":["Small; little."]}]},
"красивый":{"pos":[{"p":"adjective","d":["Beautiful; handsome."]}]},
"новый":{"pos":[{"p":"adjective","d":["New."]}]},
"важный":{"pos":[{"p":"adjective","d":["Important."]}]},
"быть":{"pos":[{"p":"verb","d":["To be."]}]},
"иметь":{"pos":[{"p":"verb","d":["To have."]}]},
"делать":{"pos":[{"p":"verb","d":["To do; to make."]}]},
"идти":{"pos":[{"p":"verb","d":["To go (on foot, one direction)."]}]},
"говорить":{"pos":[{"p":"verb","d":["To speak; to say; to talk."]}]},
"есть":{"pos":[{"p":"verb","d":["To eat; also 'there is/are'."]}]},
"видеть":{"pos":[{"p":"verb","d":["To see."]}]},
"знать":{"pos":[{"p":"verb","d":["To know."]}]},
"хотеть":{"pos":[{"p":"verb","d":["To want."]}]},
"сегодня":{"pos":[{"p":"adverb","d":["Today."]}]},
"завтра":{"pos":[{"p":"adverb","d":["Tomorrow."]}]},
"вчера":{"pos":[{"p":"adverb","d":["Yesterday."]}]},
"сейчас":{"pos":[{"p":"adverb","d":["Now."]}]},
"всегда":{"pos":[{"p":"adverb","d":["Always."]}]},
"никогда":{"pos":[{"p":"adverb","d":["Never."]}]},
"очень":{"pos":[{"p":"adverb","d":["Very."]}]},
"много":{"pos":[{"p":"adverb","d":["A lot; many; much."]}]},
"мир":{"pos":[{"p":"noun","d":["World; peace."]}]},
"школа":{"pos":[{"p":"noun","d":["School."]}]},
"мать":{"pos":[{"p":"noun","d":["Mother."]}]},
"отец":{"pos":[{"p":"noun","d":["Father."]}]},
"ребёнок":{"pos":[{"p":"noun","d":["Child."]}]},
"красный":{"pos":[{"p":"adjective","d":["Red."]}]},
"синий":{"pos":[{"p":"adjective","d":["Blue (dark)."]}]},
"зелёный":{"pos":[{"p":"adjective","d":["Green."]}]},
"белый":{"pos":[{"p":"adjective","d":["White."]}]},
"чёрный":{"pos":[{"p":"adjective","d":["Black."]}]}
};

/* ── Arabic ──────────────────────────────────────────────────────────────── */
D.ar = {
"مرحبا":{"pos":[{"p":"interjection","d":["Hello; welcome."]}]},
"السلام عليكم":{"pos":[{"p":"phrase","d":["Peace be upon you; the standard Islamic greeting."]}]},
"وعليكم السلام":{"pos":[{"p":"phrase","d":["And upon you peace; the reply to السلام عليكم."]}]},
"مع السلامة":{"pos":[{"p":"phrase","d":["Goodbye; go in peace."]}]},
"شكراً":{"pos":[{"p":"interjection","d":["Thank you."]}]},
"من فضلك":{"pos":[{"p":"phrase","d":["Please (to a male)."]}]},
"عفواً":{"pos":[{"p":"interjection","d":["Excuse me; you're welcome; sorry."]}]},
"نعم":{"pos":[{"p":"adverb","d":["Yes."]}]},
"لا":{"pos":[{"p":"adverb","d":["No."]}]},
"ماء":{"pos":[{"p":"noun","d":["Water."]}]},
"بيت":{"pos":[{"p":"noun","d":["House; home."]}]},
"شخص":{"pos":[{"p":"noun","d":["Person."]}]},
"وقت":{"pos":[{"p":"noun","d":["Time."]}]},
"عمل":{"pos":[{"p":"noun","d":["Work; job; action."]}]},
"مال":{"pos":[{"p":"noun","d":["Money; wealth."]}]},
"يوم":{"pos":[{"p":"noun","d":["Day."]}]},
"سنة":{"pos":[{"p":"noun","d":["Year."]}]},
"حياة":{"pos":[{"p":"noun","d":["Life."]}]},
"حب":{"pos":[{"p":"noun","d":["Love."]}]},
"صديق":{"pos":[{"p":"noun","d":["Friend (masculine)."]}]},
"طعام":{"pos":[{"p":"noun","d":["Food."]}]},
"اسم":{"pos":[{"p":"noun","d":["Name."]}]},
"جيد":{"pos":[{"p":"adjective","d":["Good; fine."]}]},
"سيء":{"pos":[{"p":"adjective","d":["Bad."]}]},
"كبير":{"pos":[{"p":"adjective","d":["Big; large; great; old."]}]},
"صغير":{"pos":[{"p":"adjective","d":["Small; little; young."]}]},
"جميل":{"pos":[{"p":"adjective","d":["Beautiful; nice."]}]},
"جديد":{"pos":[{"p":"adjective","d":["New."]}]},
"مهم":{"pos":[{"p":"adjective","d":["Important."]}]},
"كان":{"pos":[{"p":"verb","d":["Was; were; to be (past tense)."]}]},
"يكون":{"pos":[{"p":"verb","d":["To be (present/future)."]}]},
"عنده":{"pos":[{"p":"phrase","d":["He has; to have (possessive construction)."]}]},
"يفعل":{"pos":[{"p":"verb","d":["To do; to make."]}]},
"يذهب":{"pos":[{"p":"verb","d":["To go."]}]},
"يتكلم":{"pos":[{"p":"verb","d":["To speak; to talk."]}]},
"يأكل":{"pos":[{"p":"verb","d":["To eat."]}]},
"يرى":{"pos":[{"p":"verb","d":["To see."]}]},
"يعرف":{"pos":[{"p":"verb","d":["To know."]}]},
"اليوم":{"pos":[{"p":"adverb","d":["Today."]}]},
"غداً":{"pos":[{"p":"adverb","d":["Tomorrow."]}]},
"أمس":{"pos":[{"p":"adverb","d":["Yesterday."]}]},
"الآن":{"pos":[{"p":"adverb","d":["Now."]}]},
"دائماً":{"pos":[{"p":"adverb","d":["Always."]}]},
"أبداً":{"pos":[{"p":"adverb","d":["Never."]}]},
"جداً":{"pos":[{"p":"adverb","d":["Very; a lot."]}]},
"عالم":{"pos":[{"p":"noun","d":["World; also scholar."]}]},
"مدرسة":{"pos":[{"p":"noun","d":["School."]}]},
"أم":{"pos":[{"p":"noun","d":["Mother."]}]},
"أب":{"pos":[{"p":"noun","d":["Father."]}]},
"طفل":{"pos":[{"p":"noun","d":["Child."]}]},
"أحمر":{"pos":[{"p":"adjective","d":["Red."]}]},
"أزرق":{"pos":[{"p":"adjective","d":["Blue."]}]},
"أخضر":{"pos":[{"p":"adjective","d":["Green."]}]},
"أبيض":{"pos":[{"p":"adjective","d":["White."]}]},
"أسود":{"pos":[{"p":"adjective","d":["Black."]}]}
};

/* ── Hindi ───────────────────────────────────────────────────────────────── */
D.hi = {
"नमस्ते":{"pos":[{"p":"interjection","d":["Hello; greetings (a respectful Hindu greeting)."]}]},
"नमस्कार":{"pos":[{"p":"interjection","d":["Hello; a formal and respectful greeting."]}]},
"अलविदा":{"pos":[{"p":"interjection","d":["Goodbye; farewell."]}]},
"धन्यवाद":{"pos":[{"p":"interjection","d":["Thank you."]}]},
"शुक्रिया":{"pos":[{"p":"interjection","d":["Thank you (informal)."]}]},
"कृपया":{"pos":[{"p":"adverb","d":["Please."]}]},
"माफ करना":{"pos":[{"p":"phrase","d":["Sorry; excuse me."]}]},
"हाँ":{"pos":[{"p":"adverb","d":["Yes."]}]},
"नहीं":{"pos":[{"p":"adverb","d":["No."]}]},
"पानी":{"pos":[{"p":"noun","d":["Water."]}]},
"घर":{"pos":[{"p":"noun","d":["House; home."]}]},
"व्यक्ति":{"pos":[{"p":"noun","d":["Person."]}]},
"समय":{"pos":[{"p":"noun","d":["Time."]}]},
"काम":{"pos":[{"p":"noun","d":["Work; task."]}]},
"पैसा":{"pos":[{"p":"noun","d":["Money."]}]},
"दिन":{"pos":[{"p":"noun","d":["Day."]}]},
"साल":{"pos":[{"p":"noun","d":["Year."]}]},
"जीवन":{"pos":[{"p":"noun","d":["Life."]}]},
"प्यार":{"pos":[{"p":"noun","d":["Love."]}]},
"दोस्त":{"pos":[{"p":"noun","d":["Friend."]}]},
"खाना":{"pos":[{"p":"noun","d":["Food; meal."]}]},
"नाम":{"pos":[{"p":"noun","d":["Name."]}]},
"अच्छा":{"pos":[{"p":"adjective","d":["Good; fine; okay."]}]},
"बुरा":{"pos":[{"p":"adjective","d":["Bad."]}]},
"बड़ा":{"pos":[{"p":"adjective","d":["Big; large; great."]}]},
"छोटा":{"pos":[{"p":"adjective","d":["Small; young."]}]},
"सुंदर":{"pos":[{"p":"adjective","d":["Beautiful."]}]},
"नया":{"pos":[{"p":"adjective","d":["New."]}]},
"जरूरी":{"pos":[{"p":"adjective","d":["Important; necessary."]}]},
"होना":{"pos":[{"p":"verb","d":["To be; to happen."]}]},
"करना":{"pos":[{"p":"verb","d":["To do; to make."]}]},
"जाना":{"pos":[{"p":"verb","d":["To go."]}]},
"आना":{"pos":[{"p":"verb","d":["To come."]}]},
"बोलना":{"pos":[{"p":"verb","d":["To speak; to say."]}]},
"खाना":{"pos":[{"p":"verb","d":["To eat."]}]},
"देखना":{"pos":[{"p":"verb","d":["To see; to look."]}]},
"जानना":{"pos":[{"p":"verb","d":["To know."]}]},
"चाहना":{"pos":[{"p":"verb","d":["To want; to love."]}]},
"आज":{"pos":[{"p":"adverb","d":["Today."]}]},
"कल":{"pos":[{"p":"adverb","d":["Tomorrow; also yesterday (context-dependent)."]}]},
"अभी":{"pos":[{"p":"adverb","d":["Now; right now."]}]},
"हमेशा":{"pos":[{"p":"adverb","d":["Always."]}]},
"कभी नहीं":{"pos":[{"p":"adverb","d":["Never."]}]},
"बहुत":{"pos":[{"p":"adverb","d":["Very; very much; a lot."]}]},
"क्योंकि":{"pos":[{"p":"conjunction","d":["Because."]}]},
"लेकिन":{"pos":[{"p":"conjunction","d":["But; however."]}]},
"दुनिया":{"pos":[{"p":"noun","d":["World."]}]},
"स्कूल":{"pos":[{"p":"noun","d":["School."]}]},
"माँ":{"pos":[{"p":"noun","d":["Mother."]}]},
"पिता":{"pos":[{"p":"noun","d":["Father."]}]},
"बच्चा":{"pos":[{"p":"noun","d":["Child."]}]},
"लाल":{"pos":[{"p":"adjective","d":["Red."]}]},
"नीला":{"pos":[{"p":"adjective","d":["Blue."]}]},
"हरा":{"pos":[{"p":"adjective","d":["Green."]}]},
"सफ़ेद":{"pos":[{"p":"adjective","d":["White."]}]},
"काला":{"pos":[{"p":"adjective","d":["Black."]}]}
};

/* ── Japanese ────────────────────────────────────────────────────────────── */
D.ja = {
"こんにちは":{"pos":[{"p":"interjection","d":["Hello; good afternoon (daytime greeting)."]}]},
"おはよう":{"pos":[{"p":"interjection","d":["Good morning (informal)."]}]},
"おはようございます":{"pos":[{"p":"interjection","d":["Good morning (polite)."]}]},
"こんばんは":{"pos":[{"p":"interjection","d":["Good evening."]}]},
"さようなら":{"pos":[{"p":"interjection","d":["Goodbye."]}]},
"ありがとう":{"pos":[{"p":"interjection","d":["Thank you (informal)."]}]},
"ありがとうございます":{"pos":[{"p":"phrase","d":["Thank you very much (polite)."]}]},
"すみません":{"pos":[{"p":"interjection","d":["Excuse me; I'm sorry; thank you (versatile polite expression)."]}]},
"はい":{"pos":[{"p":"adverb","d":["Yes."]}]},
"いいえ":{"pos":[{"p":"adverb","d":["No."]}]},
"みず":{"pos":[{"p":"noun","d":["Water."]}]},
"水":{"pos":[{"p":"noun","d":["Water."]}]},
"いえ":{"pos":[{"p":"noun","d":["House; home."]}]},
"家":{"pos":[{"p":"noun","d":["House; home; family."]}]},
"ひと":{"pos":[{"p":"noun","d":["Person; people."]}]},
"人":{"pos":[{"p":"noun","d":["Person; people."]}]},
"じかん":{"pos":[{"p":"noun","d":["Time."]}]},
"時間":{"pos":[{"p":"noun","d":["Time; hour."]}]},
"しごと":{"pos":[{"p":"noun","d":["Work; job."]}]},
"仕事":{"pos":[{"p":"noun","d":["Work; job; task."]}]},
"おかね":{"pos":[{"p":"noun","d":["Money."]}]},
"お金":{"pos":[{"p":"noun","d":["Money."]}]},
"ひ":{"pos":[{"p":"noun","d":["Day; sun; fire."]}]},
"日":{"pos":[{"p":"noun","d":["Day; sun; Japan."]}]},
"とし":{"pos":[{"p":"noun","d":["Year; age."]}]},
"年":{"pos":[{"p":"noun","d":["Year."]}]},
"いのち":{"pos":[{"p":"noun","d":["Life."]}]},
"命":{"pos":[{"p":"noun","d":["Life."]}]},
"あい":{"pos":[{"p":"noun","d":["Love."]}]},
"愛":{"pos":[{"p":"noun","d":["Love."]}]},
"ともだち":{"pos":[{"p":"noun","d":["Friend."]}]},
"友達":{"pos":[{"p":"noun","d":["Friend."]}]},
"たべもの":{"pos":[{"p":"noun","d":["Food."]}]},
"食べ物":{"pos":[{"p":"noun","d":["Food."]}]},
"なまえ":{"pos":[{"p":"noun","d":["Name."]}]},
"名前":{"pos":[{"p":"noun","d":["Name."]}]},
"いい":{"pos":[{"p":"adjective","d":["Good; fine; nice."]}]},
"悪い":{"pos":[{"p":"adjective","d":["Bad; wrong."]}]},
"おおきい":{"pos":[{"p":"adjective","d":["Big; large."]}]},
"大きい":{"pos":[{"p":"adjective","d":["Big; large."]}]},
"ちいさい":{"pos":[{"p":"adjective","d":["Small; little."]}]},
"小さい":{"pos":[{"p":"adjective","d":["Small; little."]}]},
"きれい":{"pos":[{"p":"adjective","d":["Beautiful; clean; pretty."]}]},
"新しい":{"pos":[{"p":"adjective","d":["New."]}]},
"大切":{"pos":[{"p":"adjective","d":["Important; precious; dear."]}]},
"です":{"pos":[{"p":"auxiliary","d":["Polite copula: is/am/are (polite)."]}]},
"ある":{"pos":[{"p":"verb","d":["To exist (inanimate things); to have."]}]},
"いる":{"pos":[{"p":"verb","d":["To exist (animate things); to be."]}]},
"する":{"pos":[{"p":"verb","d":["To do."]}]},
"いく":{"pos":[{"p":"verb","d":["To go."]}]},
"くる":{"pos":[{"p":"verb","d":["To come."]}]},
"はなす":{"pos":[{"p":"verb","d":["To speak; to talk."]}]},
"たべる":{"pos":[{"p":"verb","d":["To eat."]}]},
"食べる":{"pos":[{"p":"verb","d":["To eat."]}]},
"みる":{"pos":[{"p":"verb","d":["To see; to look; to watch."]}]},
"しる":{"pos":[{"p":"verb","d":["To know."]}]},
"きょう":{"pos":[{"p":"noun","d":["Today."]}]},
"今日":{"pos":[{"p":"noun","d":["Today."]}]},
"あした":{"pos":[{"p":"noun","d":["Tomorrow."]}]},
"明日":{"pos":[{"p":"noun","d":["Tomorrow."]}]},
"きのう":{"pos":[{"p":"noun","d":["Yesterday."]}]},
"昨日":{"pos":[{"p":"noun","d":["Yesterday."]}]},
"いま":{"pos":[{"p":"adverb","d":["Now."]}]},
"今":{"pos":[{"p":"adverb","d":["Now."]}]},
"とても":{"pos":[{"p":"adverb","d":["Very; extremely."]}]},
"世界":{"pos":[{"p":"noun","d":["World."]}]},
"学校":{"pos":[{"p":"noun","d":["School."]}]},
"お母さん":{"pos":[{"p":"noun","d":["Mother (polite)."]}]},
"お父さん":{"pos":[{"p":"noun","d":["Father (polite)."]}]},
"子供":{"pos":[{"p":"noun","d":["Child; children."]}]},
"赤":{"pos":[{"p":"noun","d":["Red."]}]},
"青":{"pos":[{"p":"noun","d":["Blue; green (traffic light)."]}]},
"白":{"pos":[{"p":"noun","d":["White."]}]},
"黒":{"pos":[{"p":"noun","d":["Black."]}]}
};

/* ── Chinese (Simplified) ────────────────────────────────────────────────── */
D.zh = {
"你好":{"pos":[{"p":"phrase","d":["Hello; how are you."]}]},
"早上好":{"pos":[{"p":"phrase","d":["Good morning."]}]},
"晚上好":{"pos":[{"p":"phrase","d":["Good evening."]}]},
"再见":{"pos":[{"p":"phrase","d":["Goodbye; see you again."]}]},
"谢谢":{"pos":[{"p":"interjection","d":["Thank you."]}]},
"请":{"pos":[{"p":"verb","d":["Please; to invite; to request."]}]},
"对不起":{"pos":[{"p":"phrase","d":["Sorry; I apologize."]}]},
"没关系":{"pos":[{"p":"phrase","d":["It's okay; never mind; no problem."]}]},
"是":{"pos":[{"p":"verb","d":["To be; yes (affirmative)."]}]},
"不":{"pos":[{"p":"adverb","d":["No; not."]}]},
"水":{"pos":[{"p":"noun","d":["Water."]}]},
"家":{"pos":[{"p":"noun","d":["Home; family; house."]}]},
"人":{"pos":[{"p":"noun","d":["Person; people."]}]},
"时间":{"pos":[{"p":"noun","d":["Time."]}]},
"工作":{"pos":[{"p":"noun","d":["Work; job."]},{"p":"verb","d":["To work."]}]},
"钱":{"pos":[{"p":"noun","d":["Money."]}]},
"天":{"pos":[{"p":"noun","d":["Day; sky; heaven."]}]},
"年":{"pos":[{"p":"noun","d":["Year."]}]},
"生活":{"pos":[{"p":"noun","d":["Life; livelihood."]}]},
"爱":{"pos":[{"p":"noun","d":["Love."]},{"p":"verb","d":["To love."]}]},
"朋友":{"pos":[{"p":"noun","d":["Friend."]}]},
"食物":{"pos":[{"p":"noun","d":["Food."]}]},
"名字":{"pos":[{"p":"noun","d":["Name."]}]},
"好":{"pos":[{"p":"adjective","d":["Good; fine; well."]}]},
"坏":{"pos":[{"p":"adjective","d":["Bad."]}]},
"大":{"pos":[{"p":"adjective","d":["Big; large."]}]},
"小":{"pos":[{"p":"adjective","d":["Small; little."]}]},
"美":{"pos":[{"p":"adjective","d":["Beautiful."]}]},
"新":{"pos":[{"p":"adjective","d":["New."]}]},
"重要":{"pos":[{"p":"adjective","d":["Important."]}]},
"是":{"pos":[{"p":"verb","d":["To be."]}]},
"有":{"pos":[{"p":"verb","d":["To have; there is/are."]}]},
"做":{"pos":[{"p":"verb","d":["To do; to make."]}]},
"去":{"pos":[{"p":"verb","d":["To go."]}]},
"来":{"pos":[{"p":"verb","d":["To come."]}]},
"说":{"pos":[{"p":"verb","d":["To say; to speak; to talk."]}]},
"吃":{"pos":[{"p":"verb","d":["To eat."]}]},
"看":{"pos":[{"p":"verb","d":["To see; to look; to read."]}]},
"知道":{"pos":[{"p":"verb","d":["To know."]}]},
"想":{"pos":[{"p":"verb","d":["To want; to think; to miss."]}]},
"今天":{"pos":[{"p":"noun","d":["Today."]}]},
"明天":{"pos":[{"p":"noun","d":["Tomorrow."]}]},
"昨天":{"pos":[{"p":"noun","d":["Yesterday."]}]},
"现在":{"pos":[{"p":"adverb","d":["Now."]}]},
"很":{"pos":[{"p":"adverb","d":["Very."]}]},
"多":{"pos":[{"p":"adjective","d":["Many; much; more."]}]},
"世界":{"pos":[{"p":"noun","d":["World."]}]},
"学校":{"pos":[{"p":"noun","d":["School."]}]},
"妈妈":{"pos":[{"p":"noun","d":["Mother; mom."]}]},
"爸爸":{"pos":[{"p":"noun","d":["Father; dad."]}]},
"孩子":{"pos":[{"p":"noun","d":["Child; children."]}]},
"红":{"pos":[{"p":"adjective","d":["Red."]}]},
"蓝":{"pos":[{"p":"adjective","d":["Blue."]}]},
"绿":{"pos":[{"p":"adjective","d":["Green."]}]},
"白":{"pos":[{"p":"adjective","d":["White."]}]},
"黑":{"pos":[{"p":"adjective","d":["Black."]}]}
};

/* ── Korean ──────────────────────────────────────────────────────────────── */
D.ko = {
"안녕하세요":{"pos":[{"p":"interjection","d":["Hello (polite)."]}]},
"안녕":{"pos":[{"p":"interjection","d":["Hi; hello; bye (informal)."]}]},
"안녕히 가세요":{"pos":[{"p":"phrase","d":["Goodbye (said to someone leaving, polite)."]}]},
"감사합니다":{"pos":[{"p":"interjection","d":["Thank you (formal)."]}]},
"고마워":{"pos":[{"p":"interjection","d":["Thank you (informal)."]}]},
"부탁드립니다":{"pos":[{"p":"phrase","d":["Please (formal request)."]}]},
"죄송합니다":{"pos":[{"p":"interjection","d":["I'm sorry (formal)."]}]},
"네":{"pos":[{"p":"adverb","d":["Yes."]}]},
"아니요":{"pos":[{"p":"adverb","d":["No."]}]},
"물":{"pos":[{"p":"noun","d":["Water."]}]},
"집":{"pos":[{"p":"noun","d":["House; home."]}]},
"사람":{"pos":[{"p":"noun","d":["Person; people."]}]},
"시간":{"pos":[{"p":"noun","d":["Time; hour."]}]},
"일":{"pos":[{"p":"noun","d":["Work; job; one (1)."]}]},
"돈":{"pos":[{"p":"noun","d":["Money."]}]},
"날":{"pos":[{"p":"noun","d":["Day."]}]},
"해":{"pos":[{"p":"noun","d":["Sun; year."]}]},
"생활":{"pos":[{"p":"noun","d":["Life; living."]}]},
"사랑":{"pos":[{"p":"noun","d":["Love."]}]},
"친구":{"pos":[{"p":"noun","d":["Friend."]}]},
"음식":{"pos":[{"p":"noun","d":["Food."]}]},
"이름":{"pos":[{"p":"noun","d":["Name."]}]},
"좋다":{"pos":[{"p":"adjective","d":["Good; nice; fine."]}]},
"나쁘다":{"pos":[{"p":"adjective","d":["Bad."]}]},
"크다":{"pos":[{"p":"adjective","d":["Big; large."]}]},
"작다":{"pos":[{"p":"adjective","d":["Small."]}]},
"아름답다":{"pos":[{"p":"adjective","d":["Beautiful."]}]},
"새롭다":{"pos":[{"p":"adjective","d":["New."]}]},
"중요하다":{"pos":[{"p":"adjective","d":["Important."]}]},
"이다":{"pos":[{"p":"verb","d":["To be."]}]},
"있다":{"pos":[{"p":"verb","d":["To exist; to have; to be (at a place)."]}]},
"하다":{"pos":[{"p":"verb","d":["To do."]}]},
"가다":{"pos":[{"p":"verb","d":["To go."]}]},
"오다":{"pos":[{"p":"verb","d":["To come."]}]},
"말하다":{"pos":[{"p":"verb","d":["To speak; to say."]}]},
"먹다":{"pos":[{"p":"verb","d":["To eat."]}]},
"보다":{"pos":[{"p":"verb","d":["To see; to look; to watch."]}]},
"알다":{"pos":[{"p":"verb","d":["To know."]}]},
"원하다":{"pos":[{"p":"verb","d":["To want."]}]},
"오늘":{"pos":[{"p":"noun","d":["Today."]}]},
"내일":{"pos":[{"p":"noun","d":["Tomorrow."]}]},
"어제":{"pos":[{"p":"noun","d":["Yesterday."]}]},
"지금":{"pos":[{"p":"adverb","d":["Now."]}]},
"항상":{"pos":[{"p":"adverb","d":["Always."]}]},
"절대":{"pos":[{"p":"adverb","d":["Never; absolutely."]}]},
"매우":{"pos":[{"p":"adverb","d":["Very."]}]},
"많이":{"pos":[{"p":"adverb","d":["A lot; much; many."]}]},
"세계":{"pos":[{"p":"noun","d":["World."]}]},
"학교":{"pos":[{"p":"noun","d":["School."]}]},
"어머니":{"pos":[{"p":"noun","d":["Mother (formal)."]}]},
"아버지":{"pos":[{"p":"noun","d":["Father (formal)."]}]},
"아이":{"pos":[{"p":"noun","d":["Child."]}]},
"빨간":{"pos":[{"p":"adjective","d":["Red."]}]},
"파란":{"pos":[{"p":"adjective","d":["Blue."]}]},
"초록":{"pos":[{"p":"adjective","d":["Green."]}]},
"하얀":{"pos":[{"p":"adjective","d":["White."]}]},
"검은":{"pos":[{"p":"adjective","d":["Black."]}]}
};

/* ── Turkish ─────────────────────────────────────────────────────────────── */
D.tr = {
"merhaba":{"pos":[{"p":"interjection","d":["Hello; hi."]}]},
"günaydın":{"pos":[{"p":"interjection","d":["Good morning."]}]},
"iyi akşamlar":{"pos":[{"p":"phrase","d":["Good evening."]}]},
"hoşça kalın":{"pos":[{"p":"phrase","d":["Goodbye (formal)."]}]},
"görüşürüz":{"pos":[{"p":"phrase","d":["See you; goodbye (informal)."]}]},
"teşekkür ederim":{"pos":[{"p":"phrase","d":["Thank you (formal)."]}]},
"teşekkürler":{"pos":[{"p":"interjection","d":["Thanks (informal)."]}]},
"lütfen":{"pos":[{"p":"adverb","d":["Please."]}]},
"özür dilerim":{"pos":[{"p":"phrase","d":["I'm sorry; excuse me."]}]},
"evet":{"pos":[{"p":"adverb","d":["Yes."]}]},
"hayır":{"pos":[{"p":"adverb","d":["No."]}]},
"su":{"pos":[{"p":"noun","d":["Water."]}]},
"ev":{"pos":[{"p":"noun","d":["House; home."]}]},
"kişi":{"pos":[{"p":"noun","d":["Person."]}]},
"zaman":{"pos":[{"p":"noun","d":["Time."]}]},
"iş":{"pos":[{"p":"noun","d":["Work; job; business."]}]},
"para":{"pos":[{"p":"noun","d":["Money."]}]},
"gün":{"pos":[{"p":"noun","d":["Day."]}]},
"yıl":{"pos":[{"p":"noun","d":["Year."]}]},
"hayat":{"pos":[{"p":"noun","d":["Life."]}]},
"aşk":{"pos":[{"p":"noun","d":["Love."]}]},
"arkadaş":{"pos":[{"p":"noun","d":["Friend."]}]},
"yemek":{"pos":[{"p":"noun","d":["Food; meal."]},{"p":"verb","d":["To eat."]}]},
"isim":{"pos":[{"p":"noun","d":["Name."]}]},
"iyi":{"pos":[{"p":"adjective","d":["Good; fine; well."]}]},
"kötü":{"pos":[{"p":"adjective","d":["Bad."]}]},
"büyük":{"pos":[{"p":"adjective","d":["Big; large; great."]}]},
"küçük":{"pos":[{"p":"adjective","d":["Small; little."]}]},
"güzel":{"pos":[{"p":"adjective","d":["Beautiful; nice."]}]},
"yeni":{"pos":[{"p":"adjective","d":["New."]}]},
"önemli":{"pos":[{"p":"adjective","d":["Important."]}]},
"olmak":{"pos":[{"p":"verb","d":["To be; to become."]}]},
"sahip olmak":{"pos":[{"p":"verb","d":["To have; to possess."]}]},
"yapmak":{"pos":[{"p":"verb","d":["To do; to make."]}]},
"gitmek":{"pos":[{"p":"verb","d":["To go."]}]},
"gelmek":{"pos":[{"p":"verb","d":["To come."]}]},
"konuşmak":{"pos":[{"p":"verb","d":["To speak; to talk."]}]},
"yemek yemek":{"pos":[{"p":"verb","d":["To eat."]}]},
"görmek":{"pos":[{"p":"verb","d":["To see."]}]},
"bilmek":{"pos":[{"p":"verb","d":["To know."]}]},
"istemek":{"pos":[{"p":"verb","d":["To want."]}]},
"bugün":{"pos":[{"p":"adverb","d":["Today."]}]},
"yarın":{"pos":[{"p":"adverb","d":["Tomorrow."]}]},
"dün":{"pos":[{"p":"adverb","d":["Yesterday."]}]},
"şimdi":{"pos":[{"p":"adverb","d":["Now."]}]},
"her zaman":{"pos":[{"p":"adverb","d":["Always."]}]},
"hiçbir zaman":{"pos":[{"p":"adverb","d":["Never."]}]},
"çok":{"pos":[{"p":"adverb","d":["Very; much; a lot."]}]},
"çünkü":{"pos":[{"p":"conjunction","d":["Because."]}]},
"ama":{"pos":[{"p":"conjunction","d":["But; however."]}]},
"dünya":{"pos":[{"p":"noun","d":["World."]}]},
"okul":{"pos":[{"p":"noun","d":["School."]}]},
"anne":{"pos":[{"p":"noun","d":["Mother."]}]},
"baba":{"pos":[{"p":"noun","d":["Father."]}]},
"çocuk":{"pos":[{"p":"noun","d":["Child."]}]},
"kırmızı":{"pos":[{"p":"adjective","d":["Red."]}]},
"mavi":{"pos":[{"p":"adjective","d":["Blue."]}]},
"yeşil":{"pos":[{"p":"adjective","d":["Green."]}]},
"beyaz":{"pos":[{"p":"adjective","d":["White."]}]},
"siyah":{"pos":[{"p":"adjective","d":["Black."]}]}
};

return D;
})();
