// Curated list of fonts available in the font picker (all loaded via Google Fonts in index.html)
const FONT_LIST = [
    "Abril Fatface", "Albert Sans", "Alegreya", "Alfa Slab One", "Anton",
    "Architects Daughter", "Archivo", "Arial", "Arial Black", "Arvo", "Asap", "Audiowide",
    "Bangers", "Barlow", "Be Vietnam Pro", "Bebas Neue", "Bevan", "Bitter",
    "Black Ops One", "Bodoni Moda", "Boogaloo", "Bowlby One", "Bree Serif", "Bungee",
    "Cabin", "Cardo", "Catamaran", "Caveat", "Chakra Petch", "Chewy", "Cinzel",
    "Comfortaa", "Comic Sans MS", "Concert One", "Cookie", "Cormorant", "Cormorant Garamond",
    "Courgette", "Courier New", "Courier Prime", "Creepster", "Crete Round", "Crimson Text",
    "Dancing Script", "DM Mono", "DM Sans", "Domine",
    "EB Garamond", "Epilogue", "Exo 2",
    "Faustina", "Figtree", "Fira Code", "Fjalla One", "Forum", "Frank Ruhl Libre",
    "Fraunces", "Fredoka", "Frijole",
    "Gelasio", "Georgia", "Great Vibes",
    "Hanken Grotesk", "Heebo", "Hind",
    "IBM Plex Sans", "Impact", "Indie Flower", "Inter", "Italiana",
    "JetBrains Mono", "Josefin Sans", "Jost",
    "Kalam", "Kanit", "Karla",
    "Lato", "Lexend", "Libre Baskerville", "Lobster", "Lora", "Luckiest Guy",
    "Manrope", "Marcellus", "Maven Pro", "Merriweather", "Monoton", "Montserrat", "Mukta", "Mulish",
    "Noto Sans", "Noto Serif", "Nunito", "Nunito Sans",
    "Old Standard TT", "Open Sans", "Orbitron", "Oswald", "Outfit", "Overpass",
    "Pacifico", "Parisienne", "Passion One", "Patrick Hand", "Permanent Marker",
    "Playfair Display", "Plus Jakarta Sans", "Poppins", "Prata", "Press Start 2P",
    "PT Sans", "PT Serif", "Public Sans",
    "Quicksand",
    "Rajdhani", "Raleway", "Red Hat Display", "Righteous", "Roboto", "Roboto Mono",
    "Roboto Slab", "Rokkitt", "Rubik", "Russo One",
    "Sacramento", "Saira", "Sancreek", "Sarabun", "Satisfy", "Schibsted Grotesk", "Sen",
    "Shadows Into Light", "Sigmar One", "Sora", "Source Sans Pro", "Source Serif 4",
    "Space Mono", "Special Elite", "Spectral", "Squada One",
    "Tangerine", "Teko", "Times New Roman", "Titan One", "Titillium Web", "Trebuchet MS",
    "Ubuntu", "Unna", "Urbanist",
    "Varela Round", "Verdana", "Vollkorn",
    "Work Sans",
    "Yellowtail", "Yeseva One",
    "Zilla Slab",
];
